import React, {useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ArrowUpRight, Bath, BedDouble, Building2, Check, ChevronDown, Heart, Home, KeyRound, MapPin, Menu, MoveUpRight, Ruler, Search, ShieldCheck, SlidersHorizontal, Sparkles, X} from 'lucide-react';
import './style.css';
type Property={id:number,title:string,location:string,price:number,kind:string,beds:number,baths:number,area:number,image:string,tag:string,description:string};
const homes:Property[]=[
{id:1,title:'The Palm Residence',location:'New Town, Kolkata',price:9800000,kind:'Apartment',beds:3,baths:2,area:1640,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1100&q=85',tag:'Featured',description:'An elegant, light-filled home with contemporary finishes and an inviting living space.'},
{id:2,title:'Urban Courtyard Villa',location:'Salt Lake, Kolkata',price:18500000,kind:'Villa',beds:4,baths:3,area:2750,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1100&q=85',tag:'Popular',description:'Spacious interiors, refined design and room to make lasting memories.'},
{id:3,title:'The Skyline Studio',location:'Rajarhat, Kolkata',price:4600000,kind:'Apartment',beds:2,baths:1,area:980,image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1100&q=85',tag:'New',description:'A smart, stylish urban home designed for easy modern living.'},
{id:4,title:'Greenfield Land Parcel',location:'Barasat, West Bengal',price:3200000,kind:'Plot',beds:0,baths:0,area:2400,image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1100&q=85',tag:'Investment',description:'A promising illustrative land listing with generous open space.'},
{id:5,title:'The Heritage House',location:'Ballygunge, Kolkata',price:22500000,kind:'Villa',beds:4,baths:4,area:3150,image:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1100&q=85',tag:'Premium',description:'A distinctive residence with generous proportions and timeless appeal.'},
{id:6,title:'Parkside Modern Living',location:'Howrah, West Bengal',price:7100000,kind:'Apartment',beds:3,baths:2,area:1420,image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1100&q=85',tag:'New',description:'Thoughtfully planned rooms with natural light and an effortless flow.'}
];
const money=(n:number)=>n>=10000000?`₹${(n/10000000).toFixed(2)} Cr`:`₹${(n/100000).toFixed(0)} L`;
function App(){const [menu,setMenu]=useState(false),[query,setQuery]=useState(''),[type,setType]=useState('All types'),[budget,setBudget]=useState('Any budget'),[saved,setSaved]=useState<number[]>([]),[selected,setSelected]=useState<Property|null>(null),[contact,setContact]=useState(false),[sent,setSent]=useState(false),[showSaved,setShowSaved]=useState(false);
const filtered=useMemo(()=>homes.filter(h=>(!showSaved||saved.includes(h.id))&&(type==='All types'||h.kind===type)&&(!query||`${h.title} ${h.location}`.toLowerCase().includes(query.toLowerCase()))&&(budget==='Any budget'||(budget==='Under ₹50 L'?h.price<5000000:budget==='₹50 L – ₹1 Cr'?h.price>=5000000&&h.price<=10000000:h.price>10000000))),[query,type,budget,saved,showSaved]);
const toggle=(id:number)=>setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
const jump=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
return <><div className="notice">A concept experience by SmartTrust Realty <span>•</span> Listings are illustrative, not available for purchase</div><header><div className="nav shell"><a className="brand" href="#home" onClick={()=>setMenu(false)}><span className="brandmark"><Building2 size={23}/></span><span>smarttrust<span className="brandaccent">.</span><small>REALTY</small></span></a><nav className={menu?'navlinks open':'navlinks'}><a href="#home" onClick={()=>setMenu(false)}>Home</a><a href="#properties" onClick={()=>setMenu(false)}>Explore properties</a><a href="#about" onClick={()=>setMenu(false)}>Our approach</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><div className="navright"><button className="saved" onClick={()=>{setShowSaved(v=>!v);jump('properties')}} aria-label="Show saved properties"><Heart size={19} fill={showSaved?'currentColor':'none'}/><span>{saved.length}</span></button><button className="btn dark desktop" onClick={()=>{setContact(true);setSent(false)}}>Let's talk <ArrowUpRight size={16}/></button><button className="hamburger" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></div></header>
<main><section className="hero" id="home"><div className="heroimage"/><div className="heroshade"/><div className="shell herocontent"><div className="eyebrow light"><span className="dot"/> A BETTER WAY TO FIND HOME</div><h1>Spaces to live.<br/><em>Places to belong.</em></h1><p>Discover thoughtfully curated homes and investment opportunities, with clarity and confidence at every step.</p><button className="btn cream" onClick={()=>jump('properties')}>Explore properties <ArrowUpRight size={18}/></button><div className="herobottom"><span><ShieldCheck size={17}/> A more transparent property journey</span><span>01 / 03 <span className="line"/></span></div></div></section>
<section className="searchwrap shell"><div className="searchpanel"><div className="searchintro"><span className="eyebrow">START YOUR SEARCH</span><h2>Find a place that feels right.</h2></div><div className="searchcontrols"><label><span>LOCATION OR PROPERTY</span><div className="inputicon"><MapPin size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Kolkata, Rajarhat..."/></div></label><label><span>PROPERTY TYPE</span><div className="selectbox"><select value={type} onChange={e=>setType(e.target.value)}><option>All types</option><option>Apartment</option><option>Villa</option><option>Plot</option></select><ChevronDown size={16}/></div></label><label><span>PRICE RANGE</span><div className="selectbox"><select value={budget} onChange={e=>setBudget(e.target.value)}><option>Any budget</option><option>Under ₹50 L</option><option>₹50 L – ₹1 Cr</option><option>Above ₹1 Cr</option></select><ChevronDown size={16}/></div></label><button className="searchbtn" onClick={()=>jump('properties')}><Search size={19}/> Search</button></div></div></section>
<section className="section shell" id="properties"><div className="sectionhead"><div><div className="eyebrow green"><span className="dot"/> THE COLLECTION</div><h2>Explore exceptional <em>spaces.</em></h2><p>Find inspiration for your next chapter. Browse our illustrative collection.</p></div><button className="textbutton" onClick={()=>{setType('All types');setBudget('Any budget');setQuery('');setShowSaved(false)}}>View all properties <ArrowUpRight size={18}/></button></div><div className="filters"><span><SlidersHorizontal size={16}/> {showSaved?'Saved properties':'Featured properties'}</span><span>{filtered.length} results</span></div><div className="propertygrid">{filtered.map(h=><article className="property" key={h.id}><div className="propertyphoto"><img src={h.image} alt={h.title} loading="lazy"/><span className="tag">{h.tag}</span><button className="heart" onClick={()=>toggle(h.id)} aria-label={saved.includes(h.id)?'Remove favourite':'Save favourite'}><Heart size={19} fill={saved.includes(h.id)?'#bd694c':'none'} color={saved.includes(h.id)?'#bd694c':'#27342d'}/></button></div><div className="propertybody"><div className="propertytop"><span>{h.kind}</span><span><MapPin size={13}/>{h.location}</span></div><h3>{h.title}</h3><div className="propertymeta">{h.beds>0&&<span><BedDouble size={17}/>{h.beds} Beds</span>}{h.baths>0&&<span><Bath size={17}/>{h.baths} Baths</span>}<span><Ruler size={17}/>{h.area.toLocaleString('en-IN')} sq.ft.</span></div><div className="propertyfoot"><strong>{money(h.price)}</strong><button onClick={()=>setSelected(h)}>View details <ArrowUpRight size={17}/></button></div></div></article>)}</div>{filtered.length===0&&<div className="empty">No properties match your search. Try adjusting your filters.</div>}<p className="disclaimer">*All property names, prices, images, and details are sample content for demonstration only.</p></section>
<section className="about" id="about"><div className="shell aboutgrid"><div className="aboutvisual"><img src="https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=85" alt="Bright contemporary living room" loading="lazy"/><div className="floatcard"><span className="iconcircle"><ShieldCheck size={22}/></span><div><b>Built on trust</b><small>Clarity at every step</small></div></div></div><div className="aboutcopy"><div className="eyebrow green"><span className="dot"/> THE SMARTTRUST DIFFERENCE</div><h2>Real estate, with a <em>human touch.</em></h2><p>Finding a home is more than a transaction. We believe the process should feel thoughtful, informed, and personal from the very first conversation.</p><div className="values"><div><span><Search size={20}/></span><div><h3>Discover with ease</h3><p>Simple browsing tools that help you focus on what matters most.</p></div></div><div><span><ShieldCheck size={20}/></span><div><h3>Clarity before commitment</h3><p>Clear property information and a transparent approach.</p></div></div><div><span><Heart size={20}/></span><div><h3>Made around you</h3><p>Thoughtful experiences for different needs and lifestyles.</p></div></div></div><button className="btn dark" onClick={()=>jump('contact')}>Get in touch <ArrowUpRight size={17}/></button></div></div></section>
<section className="steps shell"><div className="eyebrow green">YOUR JOURNEY, SIMPLIFIED</div><h2>From searching to <em>settling in.</em></h2><div className="stepgrid"><div><span>01</span><Search/><h3>Explore</h3><p>Discover places that fit your priorities and preferences.</p></div><div><span>02</span><Home/><h3>Enquire</h3><p>Ask questions and get the information you need.</p></div><div><span>03</span><KeyRound/><h3>Move forward</h3><p>Make confident decisions with the right support.</p></div></div></section>
<section className="cta" id="contact"><div className="shell ctacontent"><div><div className="eyebrow light">YOUR NEXT CHAPTER STARTS HERE</div><h2>Let's find somewhere <em>extraordinary.</em></h2><p>Have a question or an idea? We'd love to hear from you.</p></div><button className="btn cream" onClick={()=>{setContact(true);setSent(false)}}>Send an enquiry <ArrowUpRight size={18}/></button></div></section></main>
<footer><div className="shell footergrid"><div><a className="brand footerbrand" href="#home"><span className="brandmark"><Building2 size={23}/></span><span>smarttrust<span className="brandaccent">.</span><small>REALTY</small></span></a><p>Thoughtful spaces. Confident decisions.<br/>A real estate concept built around trust.</p></div><div><b>Explore</b><a href="#properties">Properties</a><a href="#about">Our approach</a><a href="#contact">Contact</a></div><div><b>Important</b><span>Demonstration website</span><span>Not a licensed listing service</span><span>No real properties advertised</span></div></div><div className="shell footerbottom"><span>© {new Date().getFullYear()} SmartTrust Realty. Concept website.</span><span>Designed with purpose.</span></div></footer>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal detail" role="dialog" aria-modal="true" aria-label="Property details" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><img src={selected.image} alt={selected.title}/><div className="modalcontent"><span className="eyebrow green">SAMPLE {selected.kind.toUpperCase()}</span><h2>{selected.title}</h2><p><MapPin size={16}/> {selected.location}</p><h3>{money(selected.price)}</h3><p>{selected.description}</p><p className="disclaimer">Illustrative property only — not a real offer or available listing.</p><button className="btn dark" onClick={()=>{setSelected(null);setContact(true);setSent(false)}}>Ask a question <ArrowUpRight size={17}/></button></div></div></div>}
{contact&&<div className="overlay" onClick={()=>setContact(false)}><div className="modal contactmodal" role="dialog" aria-modal="true" aria-label="Contact SmartTrust Realty" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setContact(false)} aria-label="Close"><X/></button><div className="eyebrow green">GET IN TOUCH</div><h2>Start a conversation.</h2><p>This is a demo form. No message is sent or stored. Connect a secure backend before collecting real enquiries.</p>{sent?<div className="success"><Check/> Demo complete. No message was sent.<button className="btn dark" onClick={()=>setContact(false)}>Close</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Your name<input required placeholder="Full name"/></label><label>Email address<input required type="email" placeholder="you@example.com"/></label><label>What can we help with?<select required defaultValue=""><option value="" disabled>Select an option</option><option>Buying a property</option><option>Property information</option><option>General question</option></select></label><label>Message<textarea required rows={4} placeholder="Tell us a little about what you're looking for..."/></label><button className="btn dark" type="submit">Preview submission <ArrowRight size={17}/></button></form>}</div></div>}
</>}
createRoot(document.getElementById('root')!).render(<App/>);
